name: Fitbit Fetch Data
version: "1.0.0"
slug: fitbit-fetch-data
description: Ein Add-on, das Fitbit-Daten abruft und in InfluxDB speichert.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: thisisarpanghosh/fitbit-fetch-data:latest
hassio_api: true
hassio_role: default
host_network: true
auto_uart: true

schema:
  refresh_token: str
  influxdb_version: str
    # Unterstützte Versionen: 1 oder 2
  influxdb_host: str
    # Hostname oder IP-Adresse der InfluxDB-Datenbank
  influxdb_port: int
    # Port der InfluxDB-Datenbank
  influxdb_username: str
    # Benutzername für die InfluxDB-Datenbank (falls erforderlich)
  influxdb_password: str
    # Passwort für die InfluxDB-Datenbank (falls erforderlich)
  influxdb_database: str
    # Name der Datenbank in InfluxDB (für Version 1)
  influxdb_bucket: str
    # Name des Buckets in InfluxDB (für Version 2)
  influxdb_org: str
    # Name der Organisation in InfluxDB (für Version 2)
  influxdb_token: str
    # Token für die InfluxDB 2-Instanz
  influxdb_url: str
    # URL der InfluxDB 2-Instanz
  client_id: str
    # Client ID deiner Fitbit-Anwendung
  client_secret: str
    # Client Secret deiner Fitbit-Anwendung
  devicename: str
    # Name deines Fitbit-Geräts
  local_timezone: str
    # Lokale Zeitzone (z. B. 'Europe/Berlin')