schema:
  refresh_token: str
  influxdb_version: str
  influxdb_host: str
  influxdb_port: int
  influxdb_username: str
  influxdb_password: str
  influxdb_database: str
  influxdb_bucket: str
  influxdb_org: str
  influxdb_token: str
  influxdb_url: str
  client_id: str
  client_secret: str
  devicename: str
  local_timezone: str

name: Fitbit Fetch Data
version: "1.0.0"
slug: fitbit-fetch-data
description: Ein Add-on, das Fitbit-Daten abruft und in InfluxDB speichert.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: thisisarpanghosh/fitbit-fetch-data:latest
hassio_api: true
hassio_role: default
host_network: true
auto_uart: true