build_from:
  aarch64: "docker.io/library/python:3.10-slim"
  amd64: "docker.io/library/python:3.10-slim"
  armhf: "docker.io/library/python:3.10-slim"
  armv7: "docker.io/library/python:3.10-slim"
  i386: "docker.io/library/python:3.10-slim"