name: "Fitbit Fetch Data"
version: "1.0.2"
slug: "fitbit_fetch_data"
description: "Add-on to fetch Fitbit data and store it in InfluxDB"
url: "https://gitlab.fristerspace.de/demian/fitbit-ha-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "thisisarpanghosh/fitbit-fetch-data:latest"
startup: application
init: false
map:
  - addon_config:rw
hassio_api: true
hassio_role: default
host_network: true
auth_api: true
stage: stable
backup_exclude:
  - "*.log"
  - "tokens/*"

options:
  log_level: info
  refresh_token: ""
  influxdb_version: "1"
  influxdb_host: "localhost"
  influxdb_port: 8086
  influxdb_username: ""
  influxdb_password: ""
  influxdb_database: "fitbit"
  influxdb_bucket: ""
  influxdb_org: ""
  influxdb_token: ""
  influxdb_url: ""
  client_id: ""
  client_secret: ""
  devicename: ""
  local_timezone: "Europe/Berlin"

schema:
  log_level: list(debug|info|warning|error)
  refresh_token: str
  influxdb_version: list(1|2)
  influxdb_host: str
  influxdb_port: port
  influxdb_username: str
  influxdb_password: password
  influxdb_database: str?
  influxdb_bucket: str?
  influxdb_org: str?
  influxdb_token: password?
  influxdb_url: str?
  client_id: str
  client_secret: password
  devicename: str
  local_timezone: str