name: "Fitbit Fetch Data"
version: "1.0.14"
slug: "fitbit_fetch_data"
description: "Add-on to fetch Fitbit data and store it in InfluxDB"
url: "https://gitlab.fristerspace.de/demian/fitbit-ha-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
map:
  - share:rw
hassio_api: true
hassio_role: default
host_network: true
auth_api: true
stage: stable
backup_exclude:
  - "*.log"
  - "tokens/*"

options:
  refresh_token: null
  influxdb_version: "1"
  influxdb_host: "localhost"
  influxdb_port: 8086
  influxdb_username: ""
  influxdb_password: ""
  influxdb_database: "fitbit"
  client_id: null
  client_secret: null
  devicename: "Fitbit"
  local_timezone: "Europe/Berlin"

schema:
  refresh_token: str
  influxdb_version: "str"
  influxdb_host: "str"
  influxdb_port: "int"
  influxdb_username: "str"
  influxdb_password: "str"
  influxdb_database: "str"
  client_id: "str"
  client_secret: "str"
  devicename: "str"
  local_timezone: "str"