name: "Fitbit Fetch Data"
version: "1.0.1"
slug: "fitbit_fetch_data"
description: "Add-on to fetch Fitbit data and store it in InfluxDB"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "thisisarpanghosh/fitbit-fetch-data:latest"
startup: application
init: false
map:
  - addon_config:rw
hassio_api: true
hassio_role: default
host_network: true

schema:
  refresh_token: str
  influxdb_version: list(1|2)
  influxdb_host: str
  influxdb_port: port
  influxdb_username: str
  influxdb_password: password
  influxdb_database: str?
  influxdb_bucket: str?
  influxdb_org: str?
  influxdb_token: password?
  influxdb_url: str?
  client_id: str
  client_secret: password
  devicename: str
  local_timezone: str